import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { registerLicense } from "@syncfusion/ej2-base";

export const metadata: Metadata = {
  title: "Schedule Management App",
  description: "Generated by create next app",
};

registerLicense(
  "ORg4AjUWIQA/Gnt2XVhhQlJHfV5dXGRWfFN0QHNbdV54flVOcDwsT3RfQFliS39bd0FhWHxadXVdTw=="
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-full">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
